## Import the Libraries

In [396]:
import pandas as pd
import numpy as np
import os

In [397]:
os.getcwd()

'H:\\Advance Data Science\\Midterm\\historical_data1_Q12005'

In [398]:
tar = os.chdir("H:\Advance Data Science\Midterm\historical_data1_Q12005")
os.getcwd()

'H:\\Advance Data Science\\Midterm\\historical_data1_Q12005'

## Load the Data using Pandas

In [399]:
Quarter_data = pd.read_table("historical_data1_Q12005.txt",delimiter='|', header=None )

C:\Users\sweta\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


## Check if the Data is Loaded

In [400]:
Quarter_data.head(n=5)

0       1  2       3        4    5    6  7     8   9  ...  16  17  \
0  699  200505  N  203504  39300.0  000  1.0  O  56.0  42 ...  RI  SF   
1  691  200504  N  203503  36420.0   25  1.0  O  90.0  36 ...  OK  SF   
2  713  200503  N  203502  28740.0  000  1.0  O  72.0  45 ...  NY  SF   
3  719  200505  N  203504      NaN  000  1.0  S  85.0  47 ...  MO  CO   
4  656  200503  N  203502  40340.0  000  1.0  O  68.0  30 ...  MN  SF   

        18            19 20   21   22             23               24  25  
0   2800.0  F105Q1000001  C  360  2.0  Other sellers         USBANKNA NaN  
1  73000.0  F105Q1000002  N  360  1.0  Other sellers  Other servicers NaN  
2  12500.0  F105Q1000003  P  360  2.0  Other sellers  Other servicers NaN  
3  65000.0  F105Q1000004  P  360  2.0  Other sellers         USBANKNA NaN  
4  55900.0  F105Q1000005  C  360  2.0  Other sellers  Other servicers NaN  

[5 rows x 26 columns]

## Name the Columns

In [401]:
Quarter_data.columns = ['CREDIT_SCORE','FIRST_PAYMENT_DATE','FIRST_TIME_HOMEBUYER_FLAG','MATURITY_DATE','MSA','MORTGAGE_INSURANCE_PERCENTAGE_MI','NUMBER_OF_UNITS','OCCUPANCY_STATUS','ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV','ORIGINAL_DEBT_TO_INCOME_DTI_RATIO','ORIGINAL_UPB','ORIGINAL_LOAN_TO_VALUE_LTV','ORIGINAL_INTEREST_RATE','CHANNEL','PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG','PRODUCT_TYPE','PROPERTY_STATE','PROPERTY_TYPE','POSTAL_CODE','LOAN_SEQUENCE_NUMBER','LOAN_PURPOSE','ORIGINAL_LOAN_TERM','NUMBER_OF_BORROWERS','SELLER_NAME','SERVICER_NAME','SUPER_CONFORMING_FLAG']

In [402]:
numberofrows = len(Q12005_data.index)
print (numberofrows)

351739


In [403]:
Quarter_data.head(n=5)

CREDIT_SCORE  FIRST_PAYMENT_DATE FIRST_TIME_HOMEBUYER_FLAG  MATURITY_DATE  \
0          699              200505                         N         203504   
1          691              200504                         N         203503   
2          713              200503                         N         203502   
3          719              200505                         N         203504   
4          656              200503                         N         203502   

       MSA MORTGAGE_INSURANCE_PERCENTAGE_MI  NUMBER_OF_UNITS OCCUPANCY_STATUS  \
0  39300.0                              000              1.0                O   
1  36420.0                               25              1.0                O   
2  28740.0                              000              1.0                O   
3      NaN                              000              1.0                S   
4  40340.0                              000              1.0                O   

   ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV ORIGINAL_DEBT_TO_INCOME_DTI_RATIO  \
0                                  56.0                                42   
1                                  90.0                                36   
2                                  72.0                                45   
3                                  85.0                                47   
4                                  68.0                                30   

           ...           PROPERTY_STATE  PROPERTY_TYPE  POSTAL_CODE  \
0          ...                       RI             SF       2800.0   
1          ...                       OK             SF      73000.0   
2          ...                       NY             SF      12500.0   
3          ...                       MO             CO      65000.0   
4          ...                       MN             SF      55900.0   

  LOAN_SEQUENCE_NUMBER LOAN_PURPOSE ORIGINAL_LOAN_TERM NUMBER_OF_BORROWERS  \
0         F105Q1000001            C                360                 2.0   
1         F105Q1000002            N                360                 1.0   
2         F105Q1000003            P                360                 2.0   
3         F105Q1000004            P                360                 2.0   
4         F105Q1000005            C                360                 2.0   

     SELLER_NAME    SERVICER_NAME SUPER_CONFORMING_FLAG  
0  Other sellers         USBANKNA                   NaN  
1  Other sellers  Other servicers                   NaN  
2  Other sellers  Other servicers                   NaN  
3  Other sellers         USBANKNA                   NaN  
4  Other sellers  Other servicers                   NaN  

[5 rows x 26 columns]

## Check the DataTypes

In [404]:
Quarter_data.dtypes

CREDIT_SCORE                             object
FIRST_PAYMENT_DATE                        int64
FIRST_TIME_HOMEBUYER_FLAG                object
MATURITY_DATE                             int64
MSA                                     float64
MORTGAGE_INSURANCE_PERCENTAGE_MI         object
NUMBER_OF_UNITS                         float64
OCCUPANCY_STATUS                         object
ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV    float64
ORIGINAL_DEBT_TO_INCOME_DTI_RATIO        object
ORIGINAL_UPB                              int64
ORIGINAL_LOAN_TO_VALUE_LTV              float64
ORIGINAL_INTEREST_RATE                  float64
CHANNEL                                  object
PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG     object
PRODUCT_TYPE                             object
PROPERTY_STATE                           object
PROPERTY_TYPE                            object
POSTAL_CODE                             float64
LOAN_SEQUENCE_NUMBER                     object
LOAN_PURPOSE                            

## Validate the Columns

### 1) Credit Score

A number, prepared by third parties, summarizing the borrower’s creditworthiness, which may be indicative of the likelihood that the borrower will timely repay future obligations.  Generally, the credit score disclosed is the score known at the time of acquisition and is the score used to originate the mortgage.   

In [405]:
credit_score_count = Quarter_data.groupby('CREDIT_SCORE')
#Check if there is value less than 300
print (credit_score_count['CREDIT_SCORE'].count().head(n=5))
#Check if there is value greater than 850
print (credit_score_count['CREDIT_SCORE'].count().tail(n=5))

CREDIT_SCORE
       212
300    537
306      1
360      1
413      1
Name: CREDIT_SCORE, dtype: int64
CREDIT_SCORE
840    1
842    2
843    1
844    1
850    4
Name: CREDIT_SCORE, dtype: int64


#### Replace Blanks with 0 for Credit Score Column and check condition for < 300 and > 850

In [406]:
Quarter_data['CREDIT_SCORE']  = Quarter_data['CREDIT_SCORE'].convert_objects(convert_numeric=True).fillna(0)
Quarter_data['CREDIT_SCORE'] = Quarter_data['CREDIT_SCORE'].astype(int)
Quarter_data.CREDIT_SCORE[Quarter_data.CREDIT_SCORE < 300] = 0
Quarter_data.CREDIT_SCORE[Quarter_data.CREDIT_SCORE > 850] = 0
credit_score_count1 = Quarter_data.groupby('CREDIT_SCORE')
#Check if there is value less than 300
print (credit_score_count1['CREDIT_SCORE'].count().head(n=5))
#Check if there is value greater than 850
print (credit_score_count1['CREDIT_SCORE'].count().tail(n=5))

CREDIT_SCORE
0      212
300    537
306      1
360      1
413      1
Name: CREDIT_SCORE, dtype: int64
CREDIT_SCORE
840    1
842    2
843    1
844    1
850    4
Name: CREDIT_SCORE, dtype: int64


C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  if __name__ == '__main__':
C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


### 2) FIRST PAYMENT DATE

The date of the first scheduled mortgage payment due under the terms of the mortgage note. 

#### Check if there are Nulls in that colum

In [407]:
Quarter_data['FIRST_PAYMENT_DATE'].isnull().values.any()

False

### 3) FIRST TIME HOMEBUYER FLAG

Indicates whether the Borrower, or one of a group of Borrowers, is an individual who (1) is purchasing the mortgaged property, (2) will reside in the mortgaged property as a primary residence and (3) had no ownership interest (sole or joint) in a residential property during the three-year period preceding the date of the purchase of the mortgaged property. With certain limited exceptions, a displaced homemaker or single parent may also be considered a First-Time Homebuyer if the individual had no ownership interest in a residential property during the preceding three-year period other than an ownership interest in the marital residence with a spouse.  
 
Investment Properties, Second Homes and Refinance transactions are not eligible to be considered First-Time Homebuyer transactions. 

Therefore First Time Homebuyer does not apply and will be disclosed as “Not Applicable”, which will be indicated by a blank space. 

In [408]:
#Check for unique values
Quarter_data.FIRST_TIME_HOMEBUYER_FLAG.unique()

array(['N', 'Y', nan], dtype=object)

In [409]:
#Fill nan as Unknown
Quarter_data['FIRST_TIME_HOMEBUYER_FLAG'] = Quarter_data.FIRST_TIME_HOMEBUYER_FLAG.fillna('U')

In [410]:
first_time_home_buyer_flag_count = Quarter_data.groupby('FIRST_TIME_HOMEBUYER_FLAG')
print (first_time_home_buyer_flag_count['FIRST_TIME_HOMEBUYER_FLAG'].count())

FIRST_TIME_HOMEBUYER_FLAG
N    285091
U     42649
Y     23999
Name: FIRST_TIME_HOMEBUYER_FLAG, dtype: int64


### 4) MATURITY DATE

The month in which the final monthly payment on the mortgage is scheduled to be made as stated on the original mortgage note

In [411]:
Quarter_data['MATURITY_DATE'].isnull().values.any()

False

### 5) METROPOLITAN STATISTICAL AREA (MSA) OR METROPOLITAN DIVISION

This disclosure will be based on the designation of the Metropolitan Statistical Area or Metropolitan Division based on 2010 census (for Mar 2013 and May 2013 releases) and 2013 census (for Aug 2013 and Dec 2013 releases) data. Metropolitan Statistical Areas (MSAs) are defined by the United States Office of Management and Budget (OMB) and have at least one urbanized area with a population of 50,000 or more inhabitants. OMB refers to an MSA containing a single core with a population of 2.5 million or more, which may be comprised of groupings of counties, as a Metropolitan Division. 
 
If an MSA applies to a mortgaged property, the applicable five-digit value is disclosed; however, if the mortgaged property also falls within a Metropolitan Division classification, the applicable five-digit value for the Metropolitan Division takes precedence and is disclosed instead. 
 
Changes and/or updates in designations of MSAs or Metropolitan Division will not be reflected in the Single Family Historical Dataset.

1) Metropolitan Division or MSA Code.  
2) 00000 = Indicates that the area in which the mortgaged property is located is
   a) neither an MSA nor a Metropolitan Division, or b) unknown. 

In [412]:
Quarter_data['MSA'].isnull().values.any()

True

In [413]:
#Quarter_data.MSA.unique()

In [414]:
Quarter_data['MSA'] = Quarter_data.MSA.fillna(00000)

In [415]:
msa_count = Quarter_data.groupby('MSA')
print (msa_count['MSA'].count().head(5))
print (msa_count['MSA'].count().tail(5))

MSA
0.0        54797
10180.0       99
10380.0       10
10420.0      808
10500.0       91
Name: MSA, dtype: int64
MSA
49500.0      1
49620.0    643
49660.0    532
49700.0    275
49740.0    219
Name: MSA, dtype: int64


### 6) MORTGAGE INSURANCE PERCENTAGE (MI %)

The percentage of loss coverage on the loan, at the time of Freddie Mac’s purchase of the mortgage loan that a mortgage insurer is providing to cover losses incurred as a result of a default on the loan.  Only primary mortgage insurance that is purchased by the Borrower, lender or Freddie Mac is disclosed. Mortgage insurance that constitutes “credit enhancement” that is not required by Freddie Mac’s Charter is not disclosed.  
 
Amounts of mortgage insurance reported by Sellers that are less than 1% or greater than 55% will be disclosed as “Unknown,” which will be indicated by three blank spaces.  No MI will be indicated by three zeros

1% - 55%  000 =  No MI  111 = Unknown

Is 0 same as 000 ?

In [416]:
Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI'].isnull().values.any()

False

In [417]:
Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI'].unique()

array(['000', '25', '30', '12', '17', '35', '18', '32', '27', '16', '40',
       '14', '37', '20', '   ', '22', '9', 0, 25, 30, 35, 12, 17, 32, 27,
       40, 16, 37, 6, 14, 20, 22, 9, 33, 24, 18, '11', '19', '6', '33',
       '50', '13', '54', '28', '7', '8'], dtype=object)

In [418]:
Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI']  = Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI'].convert_objects(convert_numeric=True).fillna(111)
Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI'].unique()

C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  if __name__ == '__main__':


array([   0.,   25.,   30.,   12.,   17.,   35.,   18.,   32.,   27.,
         16.,   40.,   14.,   37.,   20.,  111.,   22.,    9.,    6.,
         33.,   24.,   11.,   19.,   50.,   13.,   54.,   28.,    7.,    8.])

In [419]:
Quarter_data.MORTGAGE_INSURANCE_PERCENTAGE_MI[Quarter_data.MORTGAGE_INSURANCE_PERCENTAGE_MI > 55] = 111
Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI'] = Quarter_data['MORTGAGE_INSURANCE_PERCENTAGE_MI'].astype(int)

C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [420]:
MI_count = Quarter_data.groupby('MORTGAGE_INSURANCE_PERCENTAGE_MI')
print (MI_count['MORTGAGE_INSURANCE_PERCENTAGE_MI'].count())

MORTGAGE_INSURANCE_PERCENTAGE_MI
0      302189
6        1606
7           1
8           6
9          43
11          1
12       8941
13          1
14         48
16         84
17       2317
18         66
19          2
20         42
22        111
24          1
25      18806
27        233
28          1
30      11955
32        189
33          2
35       4891
37         15
40        103
50          1
54          1
111        83
Name: MORTGAGE_INSURANCE_PERCENTAGE_MI, dtype: int64


### 7) NUMBER OF UNITS

Denotes whether the mortgage is a one-, two-, three-, or four-unit property.
three-, or four-unit property. 
 
1 = one-unit  2 = two-unit  3 = three-unit  4 = four-unit  0 = Unknown

In [421]:
Quarter_data.NUMBER_OF_UNITS.unique()

array([  1.,   2.,   3.,   4.,  nan])

#### Replace nan as 0 which is Unknown

In [422]:
Quarter_data['NUMBER_OF_UNITS'] = Quarter_data.NUMBER_OF_UNITS.fillna(0)

In [423]:
number_of_unit_count = Quarter_data.groupby('NUMBER_OF_UNITS')
print (number_of_unit_count['NUMBER_OF_UNITS'].count())

NUMBER_OF_UNITS
0.0         4
1.0    343878
2.0      6136
3.0       995
4.0       726
Name: NUMBER_OF_UNITS, dtype: int64


### 8) OCCUPANCY STATUS

Denotes whether the mortgage type is owner occupied, second home, or investment property.  

O = Owner Occupied  I = Investment Property  S = Second Home  U  = Unknown

In [424]:
Quarter_data.OCCUPANCY_STATUS.unique()

array(['O', 'S', 'I'], dtype=object)

In [425]:
Quarter_data['OCCUPANCY_STATUS'] = Quarter_data.OCCUPANCY_STATUS.fillna('U')

In [426]:
occupancy_status_count = Quarter_data.groupby('OCCUPANCY_STATUS')
print (occupancy_status_count['OCCUPANCY_STATUS'].count())

OCCUPANCY_STATUS
I     12331
O    324495
S     14913
Name: OCCUPANCY_STATUS, dtype: int64


### 9) ORIGINAL COMBINED LOAN-TO-VALUE (CLTV)

In the case of a purchase mortgage loan, the ratio is obtained by dividing the original mortgage loan amount on the note date plus any secondary mortgage loan amount disclosed by the Seller by the lesser of the mortgaged property’s appraised value on the note date or its purchase price.  In the case of a refinance mortgage loan, the ratio is obtained by dividing the original mortgage loan amount on the note date plus any secondary mortgage loan amount disclosed by the Seller by the mortgaged property’s appraised value on the note date.  If the secondary financing amount disclosed by the Seller includes a home equity line of credit, then the CLTV calculation reflects the disbursed amount at closing of the first lien mortgage loan, not the maximum loan amount available under the home equity line of credit.  In the case of a seasoned mortgage loan, if the Seller cannot warrant that the value of the mortgaged property has not declined since the note date, Freddie Mac requires that the Seller must provide a new appraisal value, which is used in the CLTV calculation.  In certain cases, where the Seller delivered a loan to Freddie Mac with a special code indicating additional secondary mortgage loan amounts, those amounts may have been included in the CLTV calculation.    
 
If the calculated CLTV is < 0 or > 200, and the LTV is > 80 and <= 200 set the CLTV to the LTV.  If the LTV is < 80 or > 200 or unknown, set the CLTV to ‘unknown.’  If the CLTV is < LTV, set the CLTV to ‘unknown.’  Unknown is indicated by a null value. 
 
This disclosure is subject to the widely varying standards originators use to verify Borrowers’ secondary mortgage loan amounts and will not be updated. 

0% - 200%  Null = Unknown = 999

In [427]:
Quarter_data.ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV.unique()

array([  56.,   90.,   72.,   85.,   68.,   94.,   77.,   80.,   95.,
         59.,   75.,   69.,   25.,   84.,   70.,   83.,   78.,   92.,
         67.,   61.,   89.,   74.,   79.,   86.,   63.,   66.,   32.,
         35.,   55.,   64.,   73.,   31.,   54.,   48.,   36.,   71.,
         49.,   87.,   50.,   88.,   60.,   44.,   52.,   76.,   47.,
         65.,   62.,   45.,   97.,   26.,   57.,   27.,   58.,   38.,
         53.,   40.,   46.,   93.,   98.,   37.,   34.,   81.,   10.,
         51.,   82.,   42.,   17.,  100.,   43.,   14.,   91.,   16.,
         20.,   39.,   21.,    8.,   99.,   30.,   96.,   19.,   41.,
         24.,   33.,   28.,   22.,   29.,   nan,   12.,   11.,  102.,
         15.,   23.,  103.,   18.,   13.,    9.,  112.,  116.,  121.,
        111.,    6.,  153.,  118.,  105.,  104.,  101.,  125.,    7.,
        110.,  115.,  107.,  108.,  117.,  119.,  123.,  106.,  114.,
        122.,  131.,  109.,  160.,  124.,  113.])

In [428]:
Quarter_data['ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV'] = Quarter_data.ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV.fillna(999)

In [429]:
cltv_count = Quarter_data.groupby('ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV')
print (cltv_count['ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV'].count().head(5))
print (cltv_count['ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV'].count().tail(5))
print (sum(cltv_count['ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV'].count()))

ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV
6.0     23
7.0     41
8.0     62
9.0     74
10.0    94
Name: ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV, dtype: int64
ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV
125.0     3
131.0     1
153.0     1
160.0     1
999.0    19
Name: ORIGINAL_COMBINED_LOAN_TO_VALUE_CLTV, dtype: int64
351739


### 10) ORIGINAL DEBT-TO-INCOME (DTI) RATIO 

Disclosure of the debt to income ratio is based on (1) the sum of the borrower's monthly debt payments, including monthly housing expenses that incorporate the mortgage payment the borrower is making at the time of the delivery of the mortgage loan to Freddie Mac, divided by (2) the total monthly income used to underwrite the borrower as of the date of the origination of the mortgage loan.  
 
Ratios greater than 65% are indicated by three (3) blank spaces and if unknown are indicated by a Null value. 
 
This disclosure is subject to the widely varying standards originators use to verify Borrowers’ assets and liabilities and will not be updated

0%< DTI <= 65%  Space(3) >65% = 70 Null = Unknown = 99

In [430]:
Quarter_data['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'].isnull().values.any()

True

In [431]:
Quarter_data['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'].unique()

array(['42', '36', '45', '47', '30', '41', '43', '34', '32', '37', '44',
       '39', '33', '24', '7', '38', '61', '2', '29', '40', '26', '54',
       '21', '31', '28', '48', '27', '12', '18', '49', '55', '58', '22',
       '46', '25', '59', '60', '52', '53', '23', '62', '16', '17', '50',
       '   ', '35', '51', '19', '14', '13', '65', '56', '15', '57', '20',
       '64', '11', '63', '8', '10', '6', '9', '5', nan, '3', '4', '1'], dtype=object)

In [432]:
Quarter_data['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'] = Quarter_data.ORIGINAL_DEBT_TO_INCOME_DTI_RATIO.fillna(99)
Quarter_data['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'] = Quarter_data.ORIGINAL_DEBT_TO_INCOME_DTI_RATIO.replace('   ',70)
Quarter_data['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'] = Quarter_data.ORIGINAL_DEBT_TO_INCOME_DTI_RATIO.fillna(99999)
ORIGINAL_DEBT_TO_INCOME_DTI_RATIO_count = Quarter_data.groupby('ORIGINAL_DEBT_TO_INCOME_DTI_RATIO')
print (ORIGINAL_DEBT_TO_INCOME_DTI_RATIO_count['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'].count().head())
print (ORIGINAL_DEBT_TO_INCOME_DTI_RATIO_count['ORIGINAL_DEBT_TO_INCOME_DTI_RATIO'].count().tail())

ORIGINAL_DEBT_TO_INCOME_DTI_RATIO
70    10504
99      454
1       107
10     1994
11     2233
Name: ORIGINAL_DEBT_TO_INCOME_DTI_RATIO, dtype: int64
ORIGINAL_DEBT_TO_INCOME_DTI_RATIO
64    1249
65    1025
7     1117
8     1409
9     1685
Name: ORIGINAL_DEBT_TO_INCOME_DTI_RATIO, dtype: int64


### 11) ORIGINAL UPB 

The UPB of the mortgage on the note date.  

Amount will be rounded to the nearest $1,000. 

In [433]:
Quarter_data['ORIGINAL_UPB'].isnull().values.any()

False

In [434]:
print (Quarter_data['ORIGINAL_UPB'].sort_values().head())
print (Quarter_data['ORIGINAL_UPB'].sort_values().tail())

349926     6000
313934     7000
341291     7000
229664     9000
294756    10000
Name: ORIGINAL_UPB, dtype: int64
180650    692000
99003     692000
127802    692000
43493     692000
116373    692000
Name: ORIGINAL_UPB, dtype: int64


### 12) ORIGINAL LOAN-TO-VALUE (LTV) 

In the case of a purchase mortgage loan, the ratio obtained by dividing the original mortgage loan amount on the note date by the lesser of the mortgaged property’s appraised value on the note date or its purchase price. 
 
In the case of a refinance mortgage loan, the ratio obtained by dividing the original mortgage loan amount on the note date and the mortgaged property’s appraised value on the note date. 
 
In the case of a seasoned mortgage loan, if the Seller cannot warrant that the value of the mortgaged property has not declined since the note date, Freddie Mac requires that the Seller must provide a new appraisal value, which is used in the LTV calculation. 
 
Ratios below 6% or greater than 105% will be disclosed as “Unknown,” indicated by three (3) blank spaces = 999.

In [435]:
print (Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV.sort_values().head())
print (Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV.sort_values().tail())

344547    6.0
282505    6.0
261221    6.0
348944    6.0
335030    6.0
Name: ORIGINAL_LOAN_TO_VALUE_LTV, dtype: float64
329697   NaN
330915   NaN
336014   NaN
341291   NaN
349926   NaN
Name: ORIGINAL_LOAN_TO_VALUE_LTV, dtype: float64


In [436]:
Quarter_data['ORIGINAL_LOAN_TO_VALUE_LTV'] = Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV.fillna(999)
Quarter_data['ORIGINAL_LOAN_TO_VALUE_LTV'] = Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV.astype(int)

Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV[Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV < 6] = 999
Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV[Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV > 105] = 999

print (Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV.sort_values().head())
print (Quarter_data.ORIGINAL_LOAN_TO_VALUE_LTV.sort_values().tail())

295628    6
335030    6
289660    6
329504    6
35806     6
Name: ORIGINAL_LOAN_TO_VALUE_LTV, dtype: int32
336014    999
329559    999
329697    999
256685    999
313934    999
Name: ORIGINAL_LOAN_TO_VALUE_LTV, dtype: int32


C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\sweta\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


### 13) ORIGINAL INTEREST RATE 

The original note rate as indicated on the mortgage note. 

In [437]:
print (Quarter_data.ORIGINAL_INTEREST_RATE.sort_values().head())
print (Quarter_data.ORIGINAL_INTEREST_RATE.sort_values().tail())

253549    3.50
253550    3.50
351728    3.50
350835    3.75
253547    3.75
Name: ORIGINAL_INTEREST_RATE, dtype: float64
351712     9.00
351718     9.80
351694     9.80
253504    10.15
351661    10.35
Name: ORIGINAL_INTEREST_RATE, dtype: float64


### 14) CHANNEL 

R = Retail  B = Broker  C = Correspondent  T = TPO Not Specified  Space = Unknown = U

In [438]:
Quarter_data.CHANNEL.unique()

array(['R', 'T', 'C', 'B'], dtype=object)

In [439]:
Quarter_data['CHANNEL'] = Quarter_data.CHANNEL.fillna('U')
Quarter_data['CHANNEL'] = Quarter_data.CHANNEL.replace(' ','U')
Quarter_data.CHANNEL.unique()

array(['R', 'T', 'C', 'B'], dtype=object)

### 15) PREPAYMENT PENALTY MORTGAGE (PPM) FLAG 

Denotes whether the mortgage is a PPM. A PPM is a mortgage with respect to which the borrower is, or at any time has been, obligated to pay a penalty in the event of certain repayments of principal. 

Y = PPM  N = Not PPM   Space (1) = Unknown = U

In [440]:
Quarter_data.PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG.unique()

array(['N', nan, 'Y'], dtype=object)

In [441]:
Quarter_data['PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG'].isnull().values.any()

True

In [442]:
Quarter_data['PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG'] = Quarter_data.PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG.fillna('U')
Quarter_data.PREPAYMENT_PENALTY_MORTGAGE_PPM_FLAG.unique()

array(['N', 'U', 'Y'], dtype=object)

### 16) PRODUCT TYPE 

Denotes that the product is a fixed-rate mortgage.

FRM – Fixed Rate Mortgage 

In [443]:
Quarter_data.PRODUCT_TYPE.unique()

array(['FRM'], dtype=object)

### 17) PROPERTY STATE 

A two-letter abbreviation indicating the state or territory within which the property securing the mortgage is located. 

AL, TX, VA, etc
UN = Unknown

In [444]:
Quarter_data.PROPERTY_STATE.unique()

array(['RI', 'OK', 'NY', 'MO', 'MN', 'IL', 'KY', 'WA', 'TX', 'FL', 'CA',
       'IN', 'NJ', 'ID', 'TN', 'KS', 'MI', 'IA', 'MT', 'GA', 'OH', 'OR',
       'ME', 'CT', 'WV', 'NH', 'VA', 'NC', 'AZ', 'NE', 'MD', 'MA', 'UT',
       'CO', 'ND', 'PA', 'SC', 'DE', 'SD', 'WI', 'AL', 'AK', 'VT', 'LA',
       'AR', 'NM', 'HI', 'DC', 'MS', 'NV', 'GU', 'WY', 'PR', 'VI'], dtype=object)

In [445]:
Quarter_data['PROPERTY_STATE'].isnull().values.any()

False

In [446]:
Quarter_data['PROPERTY_STATE'] = Q12005_data.PROPERTY_STATE.fillna('UN')

### 18) PROPERTY TYPE 

Denotes whether the property type secured by the mortgage is a condominium, leasehold, planned unit development (PUD), cooperative share, manufactured home, or Single Family home.  
 
If the Property Type is unknown, this will be indicated by two (2) blank spaces or 'UN'.

CO = Condo  LH = Leasehold  PU = PUD  MH = Manufactured Housing  SF = 1-4 Fee Simple  CP = Co-op  
Space (2) = Unknown = UN

In [447]:
Quarter_data['PROPERTY_TYPE'].isnull().values.any()

False

In [448]:
Quarter_data.PROPERTY_TYPE.unique()

array(['SF', 'CO', 'PU', 'MH', 'LH', 'CP', '  '], dtype=object)

In [449]:
Quarter_data['PROPERTY_TYPE'] = Quarter_data.PROPERTY_TYPE.replace('  ','UN')

In [450]:
Quarter_data.PROPERTY_TYPE.unique()

array(['SF', 'CO', 'PU', 'MH', 'LH', 'CP', 'UN'], dtype=object)

### 19) POSTAL CODE 

The postal code for the location of the mortgaged property 

###00, where “###” represents the first three digits of the 5digit postal code  
Space(5)= Unknown = 99999

In [451]:
Quarter_data['POSTAL_CODE'].isnull().values.any()

True

In [452]:
Quarter_data.POSTAL_CODE.unique()

array([  2800.,  73000.,  12500.,  65000.,  55900.,  62500.,  41000.,
        12400.,  98900.,  98500.,  75900.,  32000.,  61900.,  77900.,
        92800.,  42100.,  42700.,  46300.,   7000.,  83500.,  37800.,
        62400.,  67100.,  48100.,  93600.,  66000.,  32400.,  52100.,
        34700.,  62200.,  47500.,  40400.,  92200.,  49800.,  91300.,
        59900.,  40300.,  30200.,  45000.,  97100.,  66500.,  45600.,
        45300.,  62800.,  50500.,  48000.,   4200.,   6000.,  31500.,
        24700.,   3200.,  22400.,  49700.,  62000.,  27100.,  98200.,
        85000.,  61000.,  61500.,  68800.,  92500.,  99300.,  61700.,
        20600.,   6300.,  13400.,  66400.,  32600.,  51300.,  56300.,
        60400.,   6400.,   1400.,  46600.,   7700.,   4800.,  52300.,
        23000.,   4000.,  22500.,  93700.,  27800.,  32100.,  49000.,
        84600.,  84700.,  67000.,  43900.,   4500.,  67200.,  81200.,
        23200.,  28400.,  98800.,  10900.,  97500.,  60500.,  46500.,
        14800.,   19

In [453]:
Quarter_data['POSTAL_CODE'] = Quarter_data.POSTAL_CODE.fillna(99999)
postal_code_count = Quarter_data.groupby('POSTAL_CODE')
print (postal_code_count['POSTAL_CODE'].count().head())
print (postal_code_count['POSTAL_CODE'].count().tail())

POSTAL_CODE
600.0     414
700.0     540
800.0       7
900.0     633
1000.0    374
Name: POSTAL_CODE, dtype: int64
POSTAL_CODE
99600.0    174
99700.0     69
99800.0     84
99900.0     30
99999.0      2
Name: POSTAL_CODE, dtype: int64


### 20) LOAN SEQUENCE NUMBER 

Unique identifier assigned to each loan

F1YYQnXXXXXX 
 
F1 = product (Fixed Rate Mortgage);   YYQn = origination year and quarter; and,   XXXXXX = randomly assigned digits

In [454]:
Quarter_data['LOAN_SEQUENCE_NUMBER'].isnull().values.any()

False

### Each Row is UNIQUE

In [455]:
loan_sequence_number_count = Quarter_data.groupby('LOAN_SEQUENCE_NUMBER')
sum(loan_sequence_number_count['LOAN_SEQUENCE_NUMBER'].count())
#Which means each row is unique becuase sum of rows matches to the source count

351739

### 21) LOAN PURPOSE

P = Purchase  C = Cash-out Refinance  N = No Cash-out Refinance  Space = Unknown = U

In [456]:
Quarter_data['LOAN_PURPOSE'].isnull().values.any()

False

In [457]:
Quarter_data['LOAN_PURPOSE'].unique()

array(['C', 'N', 'P'], dtype=object)

In [458]:
Quarter_data['LOAN_PURPOSE'] = Quarter_data.LOAN_PURPOSE.fillna('U')
Quarter_data['LOAN_PURPOSE'].unique()

array(['C', 'N', 'P'], dtype=object)

In [459]:
loan_purpose_count = Quarter_data.groupby('LOAN_PURPOSE')
print (loan_purpose_count['LOAN_PURPOSE'].count())
print (sum(loan_purpose_count['LOAN_PURPOSE'].count()))

LOAN_PURPOSE
C    127115
N    108028
P    116596
Name: LOAN_PURPOSE, dtype: int64
351739


### 22) ORIGINAL LOAN TERM

A calculation of the number of scheduled monthly payments of the mortgage based on the First Payment Date and Maturity Date. 
 
Loans with original term of 420 or more, or 300 or less, are excluded from the Dataset if originated prior to 1/1/2005.  If loan was originated on/after 1/1/2005, this exclusion does not apply.

Calculation:  (Loan Maturity Date (MM/YY) – Loan First Payment Date (MM/YY) + 1) 

In [460]:
Quarter_data['ORIGINAL_LOAN_TERM'].isnull().values.any()

False

In [461]:
original_loan_term_count = Quarter_data.groupby('ORIGINAL_LOAN_TERM')
print (original_loan_term_count['ORIGINAL_LOAN_TERM'].count())
print (sum(original_loan_term_count['ORIGINAL_LOAN_TERM'].count()))

ORIGINAL_LOAN_TERM
60         13
72          2
84          9
92          1
93          1
96         16
100         1
102         1
103         1
108         2
119         1
120      7834
121        18
123         3
125         1
126         2
127         1
128         3
130         2
132        45
134         1
135         3
136         1
137         2
138         6
139         5
140         2
141         2
142         3
143         1
        ...  
339         3
340         7
341        10
342        20
343        18
344        15
345        21
346        22
347        23
348       167
349        28
350        40
351        80
352        56
353        68
354       111
355        48
356        30
357        20
358        22
359        73
360    251864
361         4
363         1
368         1
433         1
480         7
549         1
556         1
557         1
Name: ORIGINAL_LOAN_TERM, dtype: int64
351739


### 23) Number of Borrowers

The number of Borrower(s) who are obligated to repay the mortgage note secured by the mortgaged property. Disclosure denotes only whether there is one borrower or more than one borrower associated with the mortgage note. This disclosure will not be updated to reflect any subsequent assumption of the mortgage note. 

01 = 1 borrower  02 = > 1 borrowers  Space (2) = Unknown = 'UN'

In [462]:
Quarter_data['NUMBER_OF_BORROWERS'].isnull().values.any()

True

In [463]:
Quarter_data['NUMBER_OF_BORROWERS'].unique()

array([  2.,   1.,  nan])

In [464]:
Quarter_data['NUMBER_OF_BORROWERS'] = Quarter_data.NUMBER_OF_BORROWERS.fillna('UN')
Quarter_data['NUMBER_OF_BORROWERS'].unique()

array([2.0, 1.0, 'UN'], dtype=object)

In [465]:
number_of_borrowers_count = Quarter_data.groupby('NUMBER_OF_BORROWERS')
print (number_of_borrowers_count['NUMBER_OF_BORROWERS'].count())
print (sum(number_of_borrowers_count['NUMBER_OF_BORROWERS'].count()))

NUMBER_OF_BORROWERS
1.0    146348
2.0    205280
UN        111
Name: NUMBER_OF_BORROWERS, dtype: int64
351739


### 24) SELLER NAME

The entity acting in its capacity as a seller of mortgages to Freddie Mac at the time of acquisition Seller Name will be disclosed for sellers with a total Original UPB representing 1% or more of the total Original UPB of all loans in the Dataset for a given calendar quarter.  Otherwise, the Seller Name will be set to “Other Sellers”. 

Name of the seller, or “Other Sellers”

In [466]:
Quarter_data['SELLER_NAME'].isnull().values.any()

False

In [467]:
Quarter_data['SELLER_NAME'].unique()

array(['Other sellers', 'COUNTRYWIDE', 'TAYLOR,BEAN&WHITAKER',
       'PROVIDENTFUNDINGASSO', 'USBANKNA', 'FIFTHTHIRDBANK',
       'ABNAMROMTGEGROUP,INC', 'CHASEHOMEFINANCELLC', 'NATLCITYMTGECO',
       'WELLSFARGOBANK,NA', 'GMACMTGECORP', 'WASHINGTONMUTUALBANK',
       'FLAGSTARBANK,FSB', 'BANKOFAMERICA,NA'], dtype=object)

In [468]:
Quarter_data['SELLER_NAME'] = Quarter_data.SELLER_NAME.fillna('Other sellers')
seller_name_count = Quarter_data.groupby('SELLER_NAME')
print (seller_name_count['SELLER_NAME'].count())
print (sum(seller_name_count['SELLER_NAME'].count()))

SELLER_NAME
ABNAMROMTGEGROUP,INC    31626
BANKOFAMERICA,NA         7446
CHASEHOMEFINANCELLC     32449
COUNTRYWIDE             19948
FIFTHTHIRDBANK           5780
FLAGSTARBANK,FSB         3835
GMACMTGECORP             9677
NATLCITYMTGECO          20235
Other sellers           56083
PROVIDENTFUNDINGASSO     4350
TAYLOR,BEAN&WHITAKER     9530
USBANKNA                16531
WASHINGTONMUTUALBANK    46306
WELLSFARGOBANK,NA       87943
Name: SELLER_NAME, dtype: int64
351739


### 25) SERVICER NAME 

The entity acting in its capacity as the servicer of mortgages to Freddie Mac as of the last period for which loan activity is reported in the Dataset.   
 
Servicer Name will be disclosed for servicers with a total Original UPB representing 1% or more of the total Original UPB of all loans in the Dataset for a given calendar quarter.  Otherwise, the Servicer Name will be set to “Other Servicers”. 

Name of the servicer, or “Other Servicers” 

In [469]:
Quarter_data['SERVICER_NAME'].isnull().values.any()

False

In [470]:
Quarter_data['SERVICER_NAME'].unique()

array(['USBANKNA', 'Other servicers', 'PNCMTGESERVICES,INC',
       'WELLSFARGOBANK,NA', 'WASHINGTONMUTUALBANK', 'PNCBANK,NATL',
       'NATLCITYMTGECO', 'JPMORGANCHASEBANK,NA', 'COUNTRYWIDE',
       'BANKOFAMERICA,NA', 'BACHOMELOANSERVICING', 'CITIMORTGAGE,INC',
       'PROVIDENTFUNDINGASSO', 'ABNAMROMTGEGROUP,INC', 'NATIONSTARMTGELLC',
       'FIFTHTHIRDBANK', 'GMACMORTGAGE,LLC'], dtype=object)

In [471]:
Quarter_data['SERVICER_NAME'] = Quarter_data.SERVICER_NAME.fillna('Other servicers')
servicer_name_count = Quarter_data.groupby('SERVICER_NAME')
print (servicer_name_count['SERVICER_NAME'].count())
print (sum(servicer_name_count['SERVICER_NAME'].count()))

SERVICER_NAME
ABNAMROMTGEGROUP,INC      6475
BACHOMELOANSERVICING      3407
BANKOFAMERICA,NA         13890
CITIMORTGAGE,INC         27529
COUNTRYWIDE               7220
FIFTHTHIRDBANK            4767
GMACMORTGAGE,LLC          5013
JPMORGANCHASEBANK,NA     53005
NATIONSTARMTGELLC         8520
NATLCITYMTGECO            6386
Other servicers          59756
PNCBANK,NATL              7609
PNCMTGESERVICES,INC       4911
PROVIDENTFUNDINGASSO      4336
USBANKNA                 17388
WASHINGTONMUTUALBANK      8881
WELLSFARGOBANK,NA       112646
Name: SERVICER_NAME, dtype: int64
351739


### 26) Super Conforming Flag

For mortgages that exceed conforming loan limits with origination dates on or after 10/1/2008 and settlements on or after 1/1/2009 

Y = Yes  Space (1)  = Not Super Conforming = N

In [472]:
Quarter_data['SUPER_CONFORMING_FLAG'].isnull().values.any()

True

In [473]:
Quarter_data['SUPER_CONFORMING_FLAG'].unique()

array([ nan])

In [474]:
Quarter_data['SUPER_CONFORMING_FLAG'] = Quarter_data.SUPER_CONFORMING_FLAG.fillna('N')
scf_count = Quarter_data.groupby('SUPER_CONFORMING_FLAG')
print (scf_count['SUPER_CONFORMING_FLAG'].count())
print (sum(scf_count['SUPER_CONFORMING_FLAG'].count()))

SUPER_CONFORMING_FLAG
N    351739
Name: SUPER_CONFORMING_FLAG, dtype: int64
351739
